### ISSUE TITLE
'dict object' has no attribute 'luci_openwisp'

### ISSUE THREAD

**Issue by mikysal78** [openwisp/ansible-openwisp2-imagegenerator#10]
La compilazione non va a termine.
https://pastebin.com/aGBGM9GQ

**Comment by nemesifier** [comment]
@mikysal78 fixato finalmente, questo è il fix: https://github.com/openwisp/ansible-openwisp2-imagegenerator/commit/31e5a44487aad3f1131422d454c719ee7b72e823
