### ISSUE TITLE
build-images.sh seems incomplete

### ISSUE THREAD

**Issue by ardavanhashemzadeh** [openwisp/ansible-openwisp2-imagegenerator#14]
Hello,
I'm new to the project and following the readme in order to build an image with openwisp-config baked in. The task ./build-images.sh fails, and examining the contents of the file I suspect it may be incomplete. Also, examining the file with nano reveals green highlighting where I suspect dynamically generated content should be.

<img width="328" alt="screen shot 2018-07-07 at 3 14 24 pm" src="https://user-images.githubusercontent.com/23556924/42413911-8bd43510-81f8-11e8-8a4c-efd184efb79b.png">

**Comment by ardavanhashemzadeh** [comment]
The green highlights are trailing spaces, and I can see what is missing by comparing to build-images.sh.jinja2, however I'm not sure how to trace the precise source of the problem.

**Comment by ardavanhashemzadeh** [comment]
I love open source, my problem was that I did not have a 'flavour' defined, so a whole for block was skipped.

**Comment by nemesifier** [comment]
There should be a default flavour  defined unless it was overwritten by mistake..

**Comment by ardavanhashemzadeh** [comment]
Thank you, this was my first time using ansible and only my second time compiling firmware so I was a bit rusty. I am loving the OpenWisp project and hope to make meaningful contributions!
