### ISSUE TITLE
Make openwrt 18.06 default

### ISSUE THREAD

**Issue by nemesifier** [openwisp/ansible-openwisp2-imagegenerator#16]
Make openwrt 18.06 the default.

Shouldn't be hard, see these lines:

- https://github.com/ninuxorg/ansible-nnxx/blob/master/chilli.yml#L10-L11
- https://github.com/ninuxorg/ansible-nnxx/blob/master/chilli.yml#L44-L57

**Comment by EdgeKing810** [comment]
But it's already version "18.06" :/
So... what should I do?
