### ISSUE TITLE
[docs] OpenWRT version in README is outdated

### ISSUE THREAD

**Issue by outbackdingo** [openwisp/ansible-openwisp2-imagegenerator#25]
states 18.06 which is dated, can it do 21.02 ??

This playbook will let you compile firmware images for an organization named snakeoil using only the standard flavour (which includes a default OpenWRT 18.06 image with the standard OpenWISP2 modules) for two architectures, ar71xx and x86.

**Comment by nemesisdesign** [comment]
The default is 19.07:

https://github.com/openwisp/ansible-openwisp2-imagegenerator/blob/9cfa55fc2e8071675b8587d1f49e7ed96bbdfd57/defaults/main.yml#L26

Maybe the README is outdated (I may have forgot to update it). Please open issues with meaningful titles, the original title is not helpful to us.

I am not sure about 21.02, I haven't tried recently, the last time I tried about 6 months ago it didn't work.

**Comment by nemesisdesign** [comment]
Closed by https://github.com/openwisp/ansible-openwisp2-imagegenerator/commit/ecbe3972d594770ee595dff4e24403b13bae590e.
