### ISSUE TITLE
[Updated on 7 Jun 2021] is it old project?

### ISSUE THREAD

**Issue by mikysal78** [openwisp/ansible-openwisp2-imagegenerator#31]
If it's an abandoned project, can you explain how to compile a full firmware for openwisp?
Thanks.

**Comment by nemesifier** [comment]
It's not an abandoned project, but please use a simpler way of compiling your firmware because you are not working for a corporation and you don't need this kind of complexity nor I can help you in maintaining your setup.

**Comment by mikysal78** [comment]
I cant't help you for maintaining my setup.
I not working for a corporation, but for a community ninux.org (basilicata) and simpler way is openwisp-imagegenerator for muti device (tp-link, linksys, gilnet, etc...).
I just pointed out that it worked before.
Now my playbook doesn't work ... ok!
But the playbook in example doesn't work either.
I try with debian 10 and 11.
Thanks.
