### ISSUE TITLE
Make password management easier

### ISSUE THREAD

**Issue by nemesifier** [openwisp/ansible-openwisp2-imagegenerator#4]
The current way to add passwords to the playbook files is cumbersome: one has to generate the password by hand on a router and then copy part of the `/etc/shadow` file in the YAML file.

It is not hard to let users define their passwords and salts in clear text in the YAML and then let the role take care of turning those clear text passwords in correctly hashed strings.

```python
import crypt;
print(crypt.crypt('password', '$1$openwisp$'))
```

Will return `$1$openwisp$iQpdG2IrO4lya98cODuUB/`, which is the password example now present in the README for `luci_openwisp`.

**Update**: [asked for a suggestion on stackoverflow, see "Generate ansible role variable locally"](http://stackoverflow.com/questions/41955615/generate-ansible-role-variable-locally/41955815).

**Comment by riblo** [comment]
Closed by	18affc3
